name = "fivezzza"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding      = "DB"
database_name = "fivezzza-db"
database_id   = "bf4a0c68-08a4-4964-a63c-b5d6d3257796"
